#!/usr/bin/env python

import sys
import subprocess
import os
import time
from datetime import datetime, timedelta
from utils import ENVIRONMENT

def bundle():
    cmd = "gomplate -f /etc/nginx/spec.conf -o /etc/nginx/nginx.conf"
    subprocess.run(cmd, shell=True, check=True)


if __name__ == "__main__":
    bundle()
    subprocess.run("/usr/sbin/nginx -g 'daemon off;'", shell=True, check=True)
