#!/usr/bin/env python

import sys
import subprocess
import os

ENVIRONMENT = os.getenv("INVENDA_ENVIRONMENT")

def watch():
    pass


def start():
    arg = " ".join(sys.argv[1:])
    subprocess.run(arg, shell=True)


if __name__ == "__main__":
    print("Starting NGINX.")

    if ENVIRONMENT == "development":
        watch()
    
    start()
