#!/usr/bin/env python

import sys
import subprocess

if __name__ == "__main__":
    if len(sys.argv) != 2 or sys.argv[1] not in ["typescript", "go"]:
        print("Usage: devscripts/openapi-spec [typescript|go]")
        exit(0)

    target = ""
    output = ""
    match sys.argv[1]:
        case "typescript":
            target = "typescript-axios"
            output = "/app/src/lib/client"
        case "go":
            target = "go-resty"
            output = "/go/src/github.com/heiytor/invenda/api/pkg/client"

    flags = ["--skip-validate-spec",
            "-i http://openapi:8080/openapi.json",
            f"-g {target}",
            f"-o {output}"]

    cmd = f"docker compose exec ui openapi-generator-cli generate {' '.join(flags)}" 
    subprocess.run(cmd, shell=True, check=True)

    print("Openapi client generated.")
