root = "."

[build]
  cmd = "go build -o ./tmp/main ./cmd/..."
  bin = "tmp/main"
  include_dir = ["cmd", "pkg", "route", "service", "store"]
  include_ext = ["go"]
  exclude_regex = ["_test\\.go"]
  exclude_unchanged = false
  delay = 1000
  kill_delay = "0s"
  stop_on_error = true

[misc]
  clean_on_exit = true
