#!/usr/bin/env python

from utils import ENVIRONMENT, Watcher

if __name__ == "__main__":
    if ENVIRONMENT == "development":
        Watcher("/go/src/github.com/heiytor/invenda/api/cmd", backend="air").start()
