openapi: 3.0.3

info:
  title: Invenda API
  version: '0.0.1'
  description: A simple API to demonstrate OpenAPI specification

servers:
  - url: https://cloud.invenda.com

tags:
  - name: auth
    description: |
      PLACEHOLDER
  - name: user
    description: |
      PLACEHOLDER
  - name: namespace
    description: |
      PLACEHOLDER

paths:
  /api/user:
    $ref: paths/api@user.yaml
  /api/user/auth:
    $ref: paths/api@user@auth.yaml
  /api/namespace:
    $ref: paths/api@namespace.yaml
  /api/namespaces:
    $ref: paths/api@namespaces.yaml
